import type { Tool } from '@/types/tool';

export const seedTools: Tool[] = [
  {
    name: 'Notion AI',
    slug: 'notion-ai',
    description: 'AI assistant for writing, summarizing, and organizing content directly inside Notion workspaces.',
    categories: ['productivity', 'writing', 'knowledge'],
    pricing: 'Freemium',
    website: 'https://www.notion.so/product/ai',
    rating: 4.6,
    rankingScore: 0,
    tags: ['notes', 'knowledge base', 'docs', 'assistant'],
    bestFor: ['founders shipping docs', 'teams centralizing knowledge', 'lightweight writing workflows'],
    pros: ['Native to Notion', 'Great for summarizing long docs', 'Familiar UX'],
    cons: ['Locked into Notion', 'Limited customization'],
    createdAt: new Date()
  },
  {
    name: 'Perplexity',
    slug: 'perplexity',
    description: 'Answer engine that combines large language models with live web sources.',
    categories: ['research', 'search'],
    pricing: 'Freemium',
    website: 'https://www.perplexity.ai',
    rating: 4.8,
    rankingScore: 0,
    tags: ['search', 'research', 'copilot'],
    bestFor: ['fast research', 'founder due diligence', 'competitive analysis'],
    pros: ['Cited sources', 'Fast UX', 'Strong for research'],
    cons: ['Can still hallucinate', 'UI optimized for power users'],
    createdAt: new Date()
  },
  {
    name: 'Midjourney',
    slug: 'midjourney',
    description: 'High-quality generative image model with a tastefully opinionated visual style.',
    categories: ['design', 'images'],
    pricing: 'Paid',
    website: 'https://www.midjourney.com',
    rating: 4.7,
    rankingScore: 0,
    tags: ['images', 'art', 'concepting'],
    bestFor: ['brand explorations', 'moodboards', 'concept art'],
    pros: ['Distinct aesthetic', 'High fidelity outputs'],
    cons: ['Discord-based workflow', 'No formal API'],
    createdAt: new Date()
  },
  {
    name: 'Claude',
    slug: 'claude',
    description: 'Helpful AI assistant with strong reasoning and long-context capabilities.',
    categories: ['assistant', 'coding', 'writing'],
    pricing: 'Freemium',
    website: 'https://www.anthropic.com',
    rating: 4.9,
    rankingScore: 0,
    tags: ['assistant', 'long context', 'analysis'],
    bestFor: ['deep analysis', 'R&D notes', 'strategic writing'],
    pros: ['Strong reasoning', 'Great for longer documents'],
    cons: ['Still evolving ecosystem'],
    createdAt: new Date()
  },
  {
    name: 'Vercel v0',
    slug: 'vercel-v0',
    description: 'Design-to-code interface that turns natural language prompts into React components.',
    categories: ['developer-tools', 'design'],
    pricing: 'Freemium',
    website: 'https://v0.dev',
    rating: 4.5,
    rankingScore: 0,
    tags: ['UI', 'React', 'prototyping'],
    bestFor: ['UI experiments', 'component exploration'],
    pros: ['Tight Next.js fit', 'Good for starting points'],
    cons: ['Not production-ready out of the box'],
    createdAt: new Date()
  },
  {
    name: 'Descript',
    slug: 'descript',
    description: 'Edit podcast and video content as easily as editing text.',
    categories: ['audio', 'video', 'productivity'],
    pricing: 'Freemium',
    website: 'https://www.descript.com',
    rating: 4.4,
    rankingScore: 0,
    tags: ['podcast', 'video editing', 'transcription'],
    bestFor: ['content creators', 'founder podcasts'],
    pros: ['Intuitive editing', 'Solid transcription'],
    cons: ['Desktop app required'],
    createdAt: new Date()
  },
  {
    name: 'Gamma',
    slug: 'gamma',
    description: 'Generate structured, minimal presentations and documents from short prompts.',
    categories: ['presentations', 'productivity'],
    pricing: 'Freemium',
    website: 'https://gamma.app',
    rating: 4.3,
    rankingScore: 0,
    tags: ['slides', 'presentations'],
    bestFor: ['pitch decks', 'internal updates'],
    pros: ['Clean templates', 'Fast to iterate'],
    cons: ['Limited customization vs. Figma'],
    createdAt: new Date()
  },
  {
    name: 'Linear Insights',
    slug: 'linear-insights',
    description: 'AI summaries and insights on top of Linear issues.',
    categories: ['developer-tools', 'productivity'],
    pricing: 'Paid',
    website: 'https://linear.app',
    rating: 4.2,
    rankingScore: 0,
    tags: ['issues', 'triage', 'summaries'],
    bestFor: ['product teams', 'engineering managers'],
    pros: ['Native to Linear', 'Useful rollups'],
    cons: ['Requires Linear', 'Opinionated workflows'],
    createdAt: new Date()
  },
  {
    name: 'Superhuman AI',
    slug: 'superhuman-ai',
    description: 'AI-powered email triage, reply suggestions, and summaries in Superhuman.',
    categories: ['email', 'productivity'],
    pricing: 'Paid',
    website: 'https://superhuman.com',
    rating: 4.1,
    rankingScore: 0,
    tags: ['email', 'inbox', 'productivity'],
    bestFor: ['busy founders', 'operators with high email volume'],
    pros: ['Fast UX', 'Great keyboard story'],
    cons: ['Requires full commitment to Superhuman'],
    createdAt: new Date()
  },
  {
    name: 'Typedream AI',
    slug: 'typedream-ai',
    description: 'Generate landing pages with AI and refine them visually.',
    categories: ['marketing', 'no-code'],
    pricing: 'Freemium',
    website: 'https://typedream.com',
    rating: 4.0,
    rankingScore: 0,
    tags: ['landing page', 'marketing site'],
    bestFor: ['MVP launches', 'waitlists', 'lightweight marketing sites'],
    pros: ['Simple editor', 'Good for non-devs'],
    cons: ['Limited customization for complex brands'],
    createdAt: new Date()
  }
];

import { Tool } from './types/tool'

export const seedTools: Tool[] = [
  {
    name: 'Astra AI',
    slug: 'astra-ai',
    description: 'AI-powered project management assistant.',
    categories: ['Productivity', 'Management'],
    pricing: 'Freemium',
    website: 'https://example.com/astra',
    rating: 4.7,
    rankingScore: 92,
    tags: ['project', 'planning', 'notion'],
    bestFor: ['PMs', 'teams'],
    pros: ['fast', 'integrations'],
    cons: ['pricing'],
    createdAt: new Date(),
    updatedAt: new Date(),
    logoUrl: ''
  },
  {
    name: 'InsightBoard',
    slug: 'insightboard',
    description: 'AI insights for decision making.',
    categories: ['Analytics'],
    pricing: 'Paid',
    website: 'https://example.com/insight',
    rating: 4.5,
    rankingScore: 85,
    tags: ['analytics', 'data', 'insights'],
    bestFor: ['C-level', 'BI'],
    pros: ['deep insights'],
    cons: ['cost'],
    createdAt: new Date(),
    updatedAt: new Date(),
    logoUrl: ''
  },
  {
    name: 'VoxelChat',
    slug: 'voxelchat',
    description: 'ChatGPT-like assistant for docs.',
    categories: ['Communication'],
    pricing: 'Freemium',
    website: 'https://example.com/voxel',
    rating: 4.2,
    rankingScore: 78,
    tags: ['chat', 'docs'],
    bestFor: ['Doc teams'],
    pros: ['easy to use'],
    cons: ['limited offline'],
    createdAt: new Date(),
    updatedAt: new Date(),
    logoUrl: ''
  },
  {
    name: 'PromptPilot',
    slug: 'promptpilot',
    description: 'Prompt engineering toolkit.',
    categories: ['Developer Tools'],
    pricing: 'Freemium',
    website: 'https://example.com/prompt',
    rating: 4.6,
    rankingScore: 88,
    tags: ['prompts', 'devtools'],
    bestFor: ['Engineers'],
    pros: ['prompts library'],
    cons: ['learning curve'],
    createdAt: new Date(),
    updatedAt: new Date(),
    logoUrl: ''
  },
  {
    name: 'ClarityAI',
    slug: 'clarity-ai',
    description: 'Clear summaries and ideas with AI.',
    categories: ['Writing'],
    pricing: 'Free',
    website: 'https://example.com/clarity',
    rating: 4.1,
    rankingScore: 76,
    tags: ['summaries', 'writing'],
    bestFor: ['Writers'],
    pros: ['clean output'],
    cons: ['limited features'],
    createdAt: new Date(),
    updatedAt: new Date(),
    logoUrl: ''
  },
  {
    name: 'Visionary',
    slug: 'visionary',
    description: 'Visual AI tooling for designers.',
    categories: ['Design'],
    pricing: 'Freemium',
    website: 'https://example.com/visionary',
    rating: 4.3,
    rankingScore: 81,
    tags: ['design', 'images'],
    bestFor: ['Design teams'],
    pros: ['image generation'],
    cons: ['compute costs'],
    createdAt: new Date(),
    updatedAt: new Date(),
    logoUrl: ''
  },
  {
    name: 'QueryPulse',
    slug: 'querypulse',
    description: 'Semantic search for teams.',
    categories: ['Search'],
    pricing: 'Freemium',
    website: 'https://example.com/query',
    rating: 4.4,
    rankingScore: 84,
    tags: ['search', 'semantic'],
    bestFor: ['Engineers', 'PM'],
    pros: ['fast'],
    cons: ['scaling'],
    createdAt: new Date(),
    updatedAt: new Date(),
    logoUrl: ''
  },
  {
    name: 'WorkflowGen',
    slug: 'workflowgen',
    description: 'Automation workflows with AI.',
    categories: ['Automation'],
    pricing: 'Paid',
    website: 'https://example.com/workflow',
    rating: 4.8,
    rankingScore: 96,
    tags: ['automation', 'workflows'],
    bestFor: ['Ops teams'],
    pros: ['robust'],
    cons: ['complex'],
    createdAt: new Date(),
    updatedAt: new Date(),
    logoUrl: ''
  },
  {
    name: 'SecureLens',
    slug: 'securelens',
    description: 'Privacy-first data tools.',
    categories: ['Security'],
    pricing: 'Freemium',
    website: 'https://example.com/secure',
    rating: 4.0,
    rankingScore: 70,
    tags: ['privacy', 'security'],
    bestFor: ['Security teams'],
    pros: ['privacy'],
    cons: ['features'],
    createdAt: new Date(),
    updatedAt: new Date(),
    logoUrl: ''
  }
]

export default seedTools
