import type { Tool } from '@/types/tool';

export const seedTools: Tool[] = [
  {
    name: 'Notion AI',
    slug: 'notion-ai',
    description: 'AI assistant for writing, summarizing, and organizing content directly inside Notion workspaces.',
    categories: ['productivity', 'writing', 'knowledge'],
    pricing: 'Freemium',
    website: 'https://www.notion.so/product/ai',
    rating: 4.6,
    rankingScore: 0,
    tags: ['notes', 'knowledge base', 'docs', 'assistant'],
    bestFor: ['founders shipping docs', 'teams centralizing knowledge', 'lightweight writing workflows'],
    pros: ['Native to Notion', 'Great for summarizing long docs', 'Familiar UX'],
    cons: ['Locked into Notion', 'Limited customization'],
    createdAt: new Date()
  },
  {
    name: 'Perplexity',
    slug: 'perplexity',
    description: 'Answer engine that combines large language models with live web sources.',
    categories: ['research', 'search'],
    pricing: 'Freemium',
    website: 'https://www.perplexity.ai',
    rating: 4.8,
    rankingScore: 0,
    tags: ['search', 'research', 'copilot'],
    bestFor: ['fast research', 'founder due diligence', 'competitive analysis'],
    pros: ['Cited sources', 'Fast UX', 'Strong for research'],
    cons: ['Can still hallucinate', 'UI optimized for power users'],
    createdAt: new Date()
  },
  {
    name: 'Midjourney',
    slug: 'midjourney',
    description: 'High-quality generative image model with a tastefully opinionated visual style.',
    categories: ['design', 'images'],
    pricing: 'Paid',
    website: 'https://www.midjourney.com',
    rating: 4.7,
    rankingScore: 0,
    tags: ['images', 'art', 'concepting'],
    bestFor: ['brand explorations', 'moodboards', 'concept art'],
    pros: ['Distinct aesthetic', 'High fidelity outputs'],
    cons: ['Discord-based workflow', 'No formal API'],
    createdAt: new Date()
  },
  {
    name: 'Claude',
    slug: 'claude',
    description: 'Helpful AI assistant with strong reasoning and long-context capabilities.',
    categories: ['assistant', 'coding', 'writing'],
    pricing: 'Freemium',
    website: 'https://www.anthropic.com',
    rating: 4.9,
    rankingScore: 0,
    tags: ['assistant', 'long context', 'analysis'],
    bestFor: ['deep analysis', 'R&D notes', 'strategic writing'],
    pros: ['Strong reasoning', 'Great for longer documents'],
    cons: ['Still evolving ecosystem'],
    createdAt: new Date()
  },
  {
    name: 'Vercel v0',
    slug: 'vercel-v0',
    description: 'Design-to-code interface that turns natural language prompts into React components.',
    categories: ['developer-tools', 'design'],
    pricing: 'Freemium',
    website: 'https://v0.dev',
    rating: 4.5,
    rankingScore: 0,
    tags: ['UI', 'React', 'prototyping'],
    bestFor: ['UI experiments', 'component exploration'],
    pros: ['Tight Next.js fit', 'Good for starting points'],
    cons: ['Not production-ready out of the box'],
    createdAt: new Date()
  },
  {
    name: 'Descript',
    slug: 'descript',
    description: 'Edit podcast and video content as easily as editing text.',
    categories: ['audio', 'video', 'productivity'],
    pricing: 'Freemium',
    website: 'https://www.descript.com',
    rating: 4.4,
    rankingScore: 0,
    tags: ['podcast', 'video editing', 'transcription'],
    bestFor: ['content creators', 'founder podcasts'],
    pros: ['Intuitive editing', 'Solid transcription'],
    cons: ['Desktop app required'],
    createdAt: new Date()
  },
  {
    name: 'Gamma',
    slug: 'gamma',
    description: 'Generate structured, minimal presentations and documents from short prompts.',
    categories: ['presentations', 'productivity'],
    pricing: 'Freemium',
    website: 'https://gamma.app',
    rating: 4.3,
    rankingScore: 0,
    tags: ['slides', 'presentations'],
    bestFor: ['pitch decks', 'internal updates'],
    pros: ['Clean templates', 'Fast to iterate'],
    cons: ['Limited customization vs. Figma'],
    createdAt: new Date()
  },
  {
    name: 'Linear Insights',
    slug: 'linear-insights',
    description: 'AI summaries and insights on top of Linear issues.',
    categories: ['developer-tools', 'productivity'],
    pricing: 'Paid',
    website: 'https://linear.app',
    rating: 4.2,
    rankingScore: 0,
    tags: ['issues', 'triage', 'summaries'],
    bestFor: ['product teams', 'engineering managers'],
    pros: ['Native to Linear', 'Useful rollups'],
    cons: ['Requires Linear', 'Opinionated workflows'],
    createdAt: new Date()
  },
  {
    name: 'Superhuman AI',
    slug: 'superhuman-ai',
    description: 'AI-powered email triage, reply suggestions, and summaries in Superhuman.',
    categories: ['email', 'productivity'],
    pricing: 'Paid',
    website: 'https://superhuman.com',
    rating: 4.1,
    rankingScore: 0,
    tags: ['email', 'inbox', 'productivity'],
    bestFor: ['busy founders', 'operators with high email volume'],
    pros: ['Fast UX', 'Great keyboard story'],
    cons: ['Requires full commitment to Superhuman'],
    createdAt: new Date()
  },
  {
    name: 'Typedream AI',
    slug: 'typedream-ai',
    description: 'Generate landing pages with AI and refine them visually.',
    categories: ['marketing', 'no-code'],
    pricing: 'Freemium',
    website: 'https://typedream.com',
    rating: 4.0,
    rankingScore: 0,
    tags: ['landing page', 'marketing site'],
    bestFor: ['MVP launches', 'waitlists', 'lightweight marketing sites'],
    pros: ['Simple editor', 'Good for non-devs'],
    cons: ['Limited customization for complex brands'],
    createdAt: new Date()
  }
];

