/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Pricing = IDL.Variant({
  'freemium' : IDL.Null,
  'free' : IDL.Null,
  'paid' : IDL.Null,
});
export const Tool = IDL.Record({
  'id' : IDL.Nat,
  'categories' : IDL.Vec(IDL.Text),
  'cons' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Time,
  'pros' : IDL.Vec(IDL.Text),
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'website' : IDL.Text,
  'rankingScore' : IDL.Nat,
  'pricing' : Pricing,
  'updatedAt' : Time,
  'rating' : IDL.Nat,
  'bestFor' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTool' : IDL.Func([Tool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getToolBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Tool)], ['query']),
  'getToolsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchTools' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Pricing = IDL.Variant({
    'freemium' : IDL.Null,
    'free' : IDL.Null,
    'paid' : IDL.Null,
  });
  const Tool = IDL.Record({
    'id' : IDL.Nat,
    'categories' : IDL.Vec(IDL.Text),
    'cons' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Time,
    'pros' : IDL.Vec(IDL.Text),
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'website' : IDL.Text,
    'rankingScore' : IDL.Nat,
    'pricing' : Pricing,
    'updatedAt' : Time,
    'rating' : IDL.Nat,
    'bestFor' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTool' : IDL.Func([Tool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllTools' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getToolBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Tool)], ['query']),
    'getToolsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchTools' : IDL.Func([IDL.Text], [IDL.Vec(Tool)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };